# Generated by Django 3.2.3 on 2022-09-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0005_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='session_id',
        ),
    ]
