# Generated by Django 3.2.3 on 2022-09-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0006_auto_20220915_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='payment_service.order'),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='payment_service.item'),
        ),
    ]
